# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NumberTileGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '13.0'

  # Pods for NumberTileGame
  #
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS/'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation/'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob/'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image/'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS/'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network/'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings/'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text/'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration/'


  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  pod 'DoubleConversion', :path => '../node_modules/react-native/third-party-podspecs/'
  pod 'glog', :path => '../node_modules/react-native/third-party-podspecs/'
  pod 'Folly', :path => '../node_modules/react-native/third-party-podspecs/'

  target 'NumberTileGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
